### ISSUE TITLE
启动后默认值是空?

### ISSUE THREAD

**Issue by ccxdd** [Nayuta403/FlutterGo#1]
demo里的文件放到工程里了跑起来后
console打印出

flutter: 发送了一次数据 0
flutter: 发送了一次数据 999999

widget并没有显示出默认值，看了原码将
_stream = StreamController.broadcast();
替换成
_stream = StreamController<T>();
再次运行

flutter: 发送了一次数据 0
flutter: 发送了一次数据 999999
flutter:  StreamBuilder<int> 中的steam接收到了一次数据0
flutter:  StreamBuilder<int> 中的steam接收到了一次数据999999

**Comment by Nayuta403** [comment]
贴下代码吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月4日(周日) 上午7:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Nayuta-D/FlutterGo] 启动后默认值是空? (#1)




 
将demo里的文件放到工程里了跑起来后
 console打印出
 
flutter: 发送了一次数据 0
 flutter: 发送了一次数据 999999
 
但widget并没有显示出来，点击多次后才显示出来。看原码不应该啊，已经Stream都已经在map中了

**Comment by ccxdd** [comment]
以解决，补了一个默认值
```dart
snapshot.data ?? widget._dataLine.currentData!
```
```dart
class _DataObserverWidgetState<T> extends State<DataObserverWidget<T>> {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: widget._dataLine.outer,
      builder: (context, AsyncSnapshot<T> snapshot) {
        return widget._builder(
            //加在这里
            context, snapshot.data ?? widget._dataLine.currentData!);
      },
    );
  }
```

**Comment by christinFu1723** [comment]
确实有这个问题，如果不修改的话，最开始widget不渲染
